project '/Users/mamikon/Xcode Projects/SocialMedia/SocialMedia.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'
use_frameworks!

target 'SocialMedia' do
  pod 'VK-ios-sdk'
end
